a = input()
b = input()
print(float(a) + float(b))
print(str(float(a))+b)
print(float(a)* float(b))
print(f'{float(a):.1f}'* int(b))
print(float(a) / float(b))
print(float(a) // float(b))
print(float(a) ** float(b))
print(float(a) % float(b))
